name: Hello world workflow
on: # events that trigger on
  push: # whenever we push to our repo main branch
    branches:
      - main
  pull_request: # whenever we pull request on the same branches
    branches:
      - main
  workflow_dispatch: # gives me a button that I can click on the ui to run this workflow without having to push changes to my repo, # whenever we manually trigger the workflow in the website button

jobs:
  hello:
    runs-on: ubuntu-latest # the operating system that we want to run our job on
    steps:
      - uses: actions/checkout@v3 # this will use and go to the github.com/actions/checkout and clone it to your repo and use the source code to run the actions, v2 is the action that we will use
      - name: hello world
        run: echo hello world
        shell: bash
  goodbye: # another jobs to run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: goodbye world
        run: echo goodbye world
        shell: bash
