name: Create a comment on new issues

on:
  issues: # this will run workflows if there's an issue comment
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJson(github.event) }}' | jq
        shell: bash # if did not pass shell it will use the default one
      # - name: Create comment
      #   uses: peter-evans/create-or-update-comment@v3
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       This is a multi-line test comment
      #       - With GitHub **Markdown** :sparkles:
      #       - Created by [create-or-update-comment][1]

      #       [1]: https://github.com/peter-evans/create-or-update-comment
      #     reactions: "+1"
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run:
          | # We will use github cli instead of using curl and to handle the params in a nicer way
          gh api -X POST \
            http:api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body="This is a comment created with the GitHub CLI from API"
        env: # To be able to work with the github cli we need to set the token otherwise it will fail or not work
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # This is a special token that is created by github and it has the permissions to do some actions on this repo only
          ORGANIZATION: ${{github.event.organization.login}}
          REPOSITORY: ${{github.event.repository.name}}
          ISSUE_NUMBER: ${{github.event.issue.number}}
