name: Create a comment on new issues

on:
  issues: # this will run workflows if there's an issue comment
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJson(github.event) }}' | jq
