name: Sync Hasura Staging
on: # events that trigger on
  push: # whenever we push to our repo develop branch
    branches:
      - develop
  workflow_dispatch: # gives me a button that I can click on the ui to run this workflow

jobs:
  sync-hasura-staging:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest # the operating system that we want to run our job on
    steps:
      - uses: actions/checkout@v2 # this will use and go to the github.com/actions/checkout and clone it to your repo and use the source code to run the actions
      - uses: actions/setup-node@v3 # setup node version
        with:
          node-version: "16.14.0"
      - name: Install Hasura CLI
        run: npm install -g hasura-cli

      - name: Sync Hasura Staging
        run: sudo chmod +x ./bin/setup-hasura-local.sh && ./bin/setup-hasura-local.sh
        env:
          HASURA_ADMIN_SECRET_STG: ${{ secrets.HASURA_ADMIN_SECRET_STG }}
          HASURA_MAIN_STG: ${{ secrets.HASURA_MAIN_STG }}

      - name: Check github logs
        run: echo Github event name and ref ${{github.event_name}} ${{github.ref}}

      - name: Check github logs
        run: echo github logs '${{ toJson(github) }}' | jq
        shell: bash # if did not pass shell it will use the default one
